# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Golang
tagline:             'Tour'
description:         'Golang Tour'
url:                 https://golang.org
baseurl:             '/go-tour'
paginate:            20
resource:            '/lessons'

# About/contact
author:
  name:              Georgekutty Joyes

# Github

github:
  repo:             https://github.com/george-kj/go-tour

# Custom vars
version:             1.0.0
