# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Golang
tagline:             'Tour'
description:         'Golang Tour'
url:                 https://golang.org
baseurl:             '/go'
paginate:            5
resource:            '/docs'

# About/contact
author:
  name:              Georgekutty Joyes

# Github

github:
  repo:             https://github.com/SGKutty/go

# Custom vars
version:             1.0.0
